- hosts: default
  tasks:
    - name: Generate room dashboard
      template:
        src: dashboard_room.yaml.j2
        dest: "{{ha_path}}/lovelace/views/dashboard_room_{{item.name | lower}}.yaml"
      with_items: "{{ha_dashboards}}"
