- hosts: default
  tasks:
    - name: Generate room dashboard
      template:
        src: room_dashboard.yaml.j2
        dest: "{{ha_path}}/lovelace/views/room_dashboard_{{item.name | lower}}.yaml"
      with_items: "{{ha_rooms}}"
